(require 'thingatpt)
(require 'eldoc)
(setq eldoc-documentation-function 'fontfile-tables-eldoc-function)

(setq fontfile-tables-eldoc-obarray (make-vector 75 0))

(set (intern "avar" fontfile-tables-eldoc-obarray) "Axis variation.")
(set (intern "acnt" fontfile-tables-eldoc-obarray) "Accent attachment.")
(set (intern "ankr" fontfile-tables-eldoc-obarray) "Anchor point.")
(set (intern "avar" fontfile-tables-eldoc-obarray) "Axis variation.")
(set (intern "BASE" fontfile-tables-eldoc-obarray) "Baseline data.")
(set (intern "bdat" fontfile-tables-eldoc-obarray) "Bitmap data.")
(set (intern "BDF" fontfile-tables-eldoc-obarray) "X11 BDF header.")
(set (intern "bhed" fontfile-tables-eldoc-obarray) "Bitmap font header.")
(set (intern "bloc" fontfile-tables-eldoc-obarray) "Bitmap location data.")
(set (intern "bsln" fontfile-tables-eldoc-obarray) "Baseline data.")
(set (intern "CBDT" fontfile-tables-eldoc-obarray) "Color bitmap data.")
(set (intern "CBLC" fontfile-tables-eldoc-obarray) "Color bitmap location data.")
(set (intern "CFF" fontfile-tables-eldoc-obarray) "Compact Font Format.")
(set (intern "cmap" fontfile-tables-eldoc-obarray) "Character to glyph mapping.")
(set (intern "COLR" fontfile-tables-eldoc-obarray) "Color table.")
(set (intern "CPAL" fontfile-tables-eldoc-obarray) "Color palette table.")
(set (intern "cvar" fontfile-tables-eldoc-obarray) "Variations on CVT table.")
(set (intern "cvt" fontfile-tables-eldoc-obarray) "Control value table.")
(set (intern "DSIG" fontfile-tables-eldoc-obarray) "Digital signature.")
(set (intern "EBDT" fontfile-tables-eldoc-obarray) "Embedded bitmap data.")
(set (intern "EBLC" fontfile-tables-eldoc-obarray) "Embedded bitmap location.")
(set (intern "EBSC" fontfile-tables-eldoc-obarray) "Embedded bitmap scaling control.")
(set (intern "fdsc" fontfile-tables-eldoc-obarray) "Font descriptor.")
(set (intern "feat" fontfile-tables-eldoc-obarray) "Layout feature table.")
(set (intern "FFTM" fontfile-tables-eldoc-obarray) "FontForge timestamp.")
(set (intern "fmtx" fontfile-tables-eldoc-obarray) "Font metrics.")
(set (intern "fond" fontfile-tables-eldoc-obarray) "Font family compatibility.")
(set (intern "fpgm" fontfile-tables-eldoc-obarray) "Font program.")
(set (intern "fvar" fontfile-tables-eldoc-obarray) "Font variation.")
(set (intern "gasp" fontfile-tables-eldoc-obarray) "Grid-fitting and scan-conversion procedure.")
(set (intern "gasp" fontfile-tables-eldoc-obarray) "Grid-fitting/Scan-conversion (optional table).")
(set (intern "GDEF" fontfile-tables-eldoc-obarray) "Glyph definition data.")
(set (intern "Glat" fontfile-tables-eldoc-obarray) "Glyph attributes table.")
(set (intern "Gloc" fontfile-tables-eldoc-obarray) "Indexes for Glat table.")
(set (intern "glyf" fontfile-tables-eldoc-obarray) "Glyph outline.")
(set (intern "GPOS" fontfile-tables-eldoc-obarray) "Glyph positioning data.")
(set (intern "GSUB" fontfile-tables-eldoc-obarray) "Glyph substitution data.")
(set (intern "gvar" fontfile-tables-eldoc-obarray) "Glyph variation.")
(set (intern "hdmx" fontfile-tables-eldoc-obarray) "Horizontal device metrics.")
(set (intern "head" fontfile-tables-eldoc-obarray) "Font header.")
(set (intern "hhea" fontfile-tables-eldoc-obarray) "Horizontal header.")
(set (intern "hmtx" fontfile-tables-eldoc-obarray) "Horizontal metrics.")
(set (intern "JSTF" fontfile-tables-eldoc-obarray) "Justification data.")
(set (intern "just" fontfile-tables-eldoc-obarray) "Justification.")
(set (intern "kern" fontfile-tables-eldoc-obarray) "Kerning.")
(set (intern "kerx" fontfile-tables-eldoc-obarray) "Extended kerning.")
(set (intern "lcar" fontfile-tables-eldoc-obarray) "Ligature caret.")
(set (intern "loca" fontfile-tables-eldoc-obarray) "Glyph location.")
(set (intern "ltag" fontfile-tables-eldoc-obarray) "Language tag.")
(set (intern "LTSH" fontfile-tables-eldoc-obarray) "Linear threshold data.")
(set (intern "MATH" fontfile-tables-eldoc-obarray) "Mathematical typesetting.")
(set (intern "maxp" fontfile-tables-eldoc-obarray) "Maximum profile.")
(set (intern "meta" fontfile-tables-eldoc-obarray) "Metadata.")
(set (intern "mort" fontfile-tables-eldoc-obarray) "Metamorphosis (deprecated).")
(set (intern "morx" fontfile-tables-eldoc-obarray) "Extended metamorphosis.")
(set (intern "name" fontfile-tables-eldoc-obarray) "Name.")
(set (intern "opbd" fontfile-tables-eldoc-obarray) "Optical bounds.")
(set (intern "OS/2" fontfile-tables-eldoc-obarray) "OS/2 and Windows specific metrics.")
(set (intern "PCLT" fontfile-tables-eldoc-obarray) "PCL 5 data.")
(set (intern "PfEd" fontfile-tables-eldoc-obarray) "FontForge's personal table.")
(set (intern "post" fontfile-tables-eldoc-obarray) "Glyph name and PostScript compatibility.")
(set (intern "prep" fontfile-tables-eldoc-obarray) "Control value program.")
(set (intern "prop" fontfile-tables-eldoc-obarray) "Glyph properties.")
(set (intern "sbix" fontfile-tables-eldoc-obarray) "Extended bitmaps.")
(set (intern "Silf" fontfile-tables-eldoc-obarray) "Main logic, including finite state machine for rule matching, constraints, and rule action code.")
(set (intern "Sill" fontfile-tables-eldoc-obarray) "Language table, containing mappings between language codes and features.")
(set (intern "SVG" fontfile-tables-eldoc-obarray) "The SVG (Scalable Vector Graphics) table.")
(set (intern "TeX" fontfile-tables-eldoc-obarray) "TeX information.")
(set (intern "trak" fontfile-tables-eldoc-obarray) "Tracking.")
(set (intern "VDMX" fontfile-tables-eldoc-obarray) "Vertical device metrics.")
(set (intern "vhea" fontfile-tables-eldoc-obarray) "Vertical Metrics header.")
(set (intern "vmtx" fontfile-tables-eldoc-obarray) "Vertical Metrics.")
(set (intern "VORG" fontfile-tables-eldoc-obarray) "Vertical Origin (optional table).")
(set (intern "xref" fontfile-tables-eldoc-obarray) "Cross-reference.")
(set (intern "Zapf" fontfile-tables-eldoc-obarray) "Glyph reference.")


(defun fontfile-tables-eldoc-function ()
    "Returns a doc string appropriate for the current context, or nil."
    (symbol-value (intern-soft (thing-at-point 'symbol)
                               fontfile-tables-eldoc-obarray)))
