(require 'thingatpt)
(require 'eldoc)
(setq eldoc-documentation-function 'fontfile-ffs-eldoc-function)

(setq fontfile-ffs-eldoc-obarray (make-vector 355 0))

(set (intern "$argc" fontfile-ffs-eldoc-obarray) "number of arguments passed to the script, including $0")
(set (intern "$argv" fontfile-ffs-eldoc-obarray) "array of arguments to the current script")
(set (intern "$curfont" fontfile-ffs-eldoc-obarray) "filename in which the current font resides")
(set (intern "$firstfont" fontfile-ffs-eldoc-obarray) "filename of the font that is first on the font list; empty if no fonts are loaded")
(set (intern "$nextfont" fontfile-ffs-eldoc-obarray) "filename of the font that follows the current font on the list; empty if $curfont is the last fone")
(set (intern "$fontchanged" fontfile-ffs-eldoc-obarray) "1 if the current font has changed, 0 if it has not changed since last read or save")
(set (intern "$fontname" fontfile-ffs-eldoc-obarray) "name contained in the postscript FontName field")
(set (intern "$familyname" fontfile-ffs-eldoc-obarray) "name contained in the postscript FamilyName field")
(set (intern "$fullname" fontfile-ffs-eldoc-obarray) "name contained in the postscript FullName field")
(set (intern "$fondname" fontfile-ffs-eldoc-obarray) "indicates what FOND the current font should be put in under Generate Mac Family")
(set (intern "$weight" fontfile-ffs-eldoc-obarray) "name contained in the postscript Weight field")
(set (intern "$copyright" fontfile-ffs-eldoc-obarray) "name contained in the postscript Notice field")
(set (intern "$filename" fontfile-ffs-eldoc-obarray) "name of the file containing the font")
(set (intern "$0" fontfile-ffs-eldoc-obarray) "current script filename")
(set (intern "$1" fontfile-ffs-eldoc-obarray) "first argument to the current script")
(set (intern "$2" fontfile-ffs-eldoc-obarray) "second argument to the current script")
(set (intern "$fontversion" fontfile-ffs-eldoc-obarray) "string containing the font's version")
(set (intern "$iscid" fontfile-ffs-eldoc-obarray) "1 if the current font is a cid keyed font, 0 if not")
(set (intern "$cidfontanme" fontfile-ffs-eldoc-obarray) "fontname of the top-level cid-keyed font; empty for non-CID fonts")
(set (intern "$mmcount" fontfile-ffs-eldoc-obarray) "number of instances in a multiple master font; 0 for non multiple master fonts")
(set (intern "$cidfamilyname" fontfile-ffs-eldoc-obarray) "family name of the top-level cid-keyed font; empty for non-CID fonts")
(set (intern "$cidfullname" fontfile-ffs-eldoc-obarray) "full fontname of the top-level cid-keyed font; empty for non-CID fonts")
(set (intern "$cidweight" fontfile-ffs-eldoc-obarray) "weight name of the top-level cid-keyed font; empty for non-CID fonts")
(set (intern "$cidcopyright" fontfile-ffs-eldoc-obarray) "copyright notice of the top-level cid-keyed font; empty for non-CID fonts")
(set (intern "$italicangle" fontfile-ffs-eldoc-obarray) "value of the postscript italic angle field")
(set (intern "$loadState" fontfile-ffs-eldoc-obarray) "bitmask of non-fatal errors encountered when loading the font")
(set (intern "$privateState" fontfile-ffs-eldoc-obarray) "bitmask of some errors in the PostScript Private dictionary")
(set (intern "$curcid" fontfile-ffs-eldoc-obarray) "fontname of the current font")
(set (intern "$firstcid" fontfile-ffs-eldoc-obarray) "fontname of the first font within this cid font")
(set (intern "$nextcid" fontfile-ffs-eldoc-obarray) "fontname of the next font within this cid font; empty if the current sub-font is the last")
(set (intern "$macstyle" fontfile-ffs-eldoc-obarray) "value of the macstyle field")
(set (intern "$bitmaps" fontfile-ffs-eldoc-obarray) "array containing all bitmap pixelsizes generated for this font")
(set (intern "$order" fontfile-ffs-eldoc-obarray) "indicates whether the font uses quadratic or cubic splines; 2 for quadratic, 3 for cubic")
(set (intern "$em" fontfile-ffs-eldoc-obarray) "number of em-units used by the font")
(set (intern "$ascent" fontfile-ffs-eldoc-obarray) "ascent of the font ")
(set (intern "$descent" fontfile-ffs-eldoc-obarray) "descent of the font ")
(set (intern "$selection" fontfile-ffs-eldoc-obarray) "integer array indicating whether each glyph in the font is selected or not; 1=selected glyph, 0=unselected")
(set (intern "$panose" fontfile-ffs-eldoc-obarray) "array containing the 10 panose values for the font")
(set (intern "$trace" fontfile-ffs-eldoc-obarray) "if set to one, then FontForge will trace each procedure call")
(set (intern "$version" fontfile-ffs-eldoc-obarray) "tring containing the current version of FontForge")
(set (intern "$haspython" fontfile-ffs-eldoc-obarray) "returns 1 if Python scripting is available, 0 if it is not")
(set (intern "Close" fontfile-ffs-eldoc-obarray) "Close()")
(set (intern "ControlAfmLigatureOutput" fontfile-ffs-eldoc-obarray) "ControlAfmLigatureOutput( script, lang, ligature-tag-list )")
(set (intern "Export" fontfile-ffs-eldoc-obarray) "Export( format [, bitmap-size] )")
(set (intern "FontsInFile" fontfile-ffs-eldoc-obarray) "FontsInFile( filename )")
(set (intern "Generate" fontfile-ffs-eldoc-obarray) "Generate( filename [, bitmaptype [, fmflags [, res [, mult-sfd-file [, namelist-name]]]]] )")
(set (intern "GenerateFamily" fontfile-ffs-eldoc-obarray) "GenerateFamily( filename, bitmaptype, fmflags, array-of-font-filenames )")
(set (intern "Import" fontfile-ffs-eldoc-obarray) "Import( filename [, toback [, flags]] )")
(set (intern "MergeKern" fontfile-ffs-eldoc-obarray) "MergeKern( filename )")
(set (intern "MergeFeature" fontfile-ffs-eldoc-obarray) "MergeFeature( filename )")
(set (intern "New" fontfile-ffs-eldoc-obarray) "New()")
(set (intern "Open" fontfile-ffs-eldoc-obarray) "Open( filename [, flags] )")
(set (intern "PrintFont" fontfile-ffs-eldoc-obarray) "PrintFont( type [, pointsize [, sample-text/filename [, output-file]]] )")
(set (intern "PrintSetup" fontfile-ffs-eldoc-obarray) "PrintSetup( type [, printer [,  width, height]] )")
(set (intern "Quit" fontfile-ffs-eldoc-obarray) "Quit( status )")
(set (intern "Revert" fontfile-ffs-eldoc-obarray) "Revert()")
(set (intern "RevertToBackup" fontfile-ffs-eldoc-obarray) "RevertToBackup()")
(set (intern "Save" fontfile-ffs-eldoc-obarray) "Save( [filename] )")
(set (intern "FileAccess" fontfile-ffs-eldoc-obarray) "FileAccess( filename [, prot] )")
(set (intern "FontImage" fontfile-ffs-eldoc-obarray) "FontImage( filename, array [, width [, height]] )")
(set (intern "LoadStringFromFile" fontfile-ffs-eldoc-obarray) "LoadStringFromFile( filename )")
(set (intern "WriteStringToFile" fontfile-ffs-eldoc-obarray) "WriteStringToFile( \"string\", \"Filename\" [, append] )")
(set (intern "Clear" fontfile-ffs-eldoc-obarray) "Clear()")
(set (intern "ClearBackground" fontfile-ffs-eldoc-obarray) "ClearBackground()")
(set (intern "Copy" fontfile-ffs-eldoc-obarray) "Copy()")
(set (intern "CopyAnchors" fontfile-ffs-eldoc-obarray) "CopyAnchors()")
(set (intern "CopyFgToBg" fontfile-ffs-eldoc-obarray) "CopyFgToBg()")
(set (intern "CopyGlyphFeatures" fontfile-ffs-eldoc-obarray) "CopyGlyphFeatures()")
(set (intern "CopyLBearing" fontfile-ffs-eldoc-obarray) "CopyLBearing()")
(set (intern "CopyRBearing" fontfile-ffs-eldoc-obarray) "CopyRBearing()")
(set (intern "CopyReference" fontfile-ffs-eldoc-obarray) "CopyReference()")
(set (intern "CopyUnlinked" fontfile-ffs-eldoc-obarray) "CopyUnlinked(")
(set (intern "CopyVWidth" fontfile-ffs-eldoc-obarray) "CopyVWidth()")
(set (intern "CopyWidth" fontfile-ffs-eldoc-obarray) "CopyWidth()")
(set (intern "Cut" fontfile-ffs-eldoc-obarray) "Cut()")
(set (intern "Join" fontfile-ffs-eldoc-obarray) "Join( [fudge] )")
(set (intern "Paste" fontfile-ffs-eldoc-obarray) "Paste()")
(set (intern "PasteInto" fontfile-ffs-eldoc-obarray) "PasteInto()")
(set (intern "PasteWithOffset" fontfile-ffs-eldoc-obarray) "PasteWithOffset( xoff, yoff )")
(set (intern "ReplaceWithReference" fontfile-ffs-eldoc-obarray) "ReplaceWithReference( [fudge] )")
(set (intern "SameGlyphAs" fontfile-ffs-eldoc-obarray) "SameGlyphAs()")
(set (intern "UnlinkReference" fontfile-ffs-eldoc-obarray) "UnlinkReference()")
(set (intern "Select" fontfile-ffs-eldoc-obarray) "Select( arg1, arg2, ... )")
(set (intern "SelectAll" fontfile-ffs-eldoc-obarray) "SelectAll()")
(set (intern "SelectAllInstancesOf" fontfile-ffs-eldoc-obarray) "SelectAllInstancesOf( name1 [, ...] )")
(set (intern "SelectBitmap" fontfile-ffs-eldoc-obarray) "SelectBitmap( size )")
(set (intern "SelectByATT" fontfile-ffs-eldoc-obarray) "SelectByATT( type, tags, contents, search-type )")
(set (intern "SelectByPosSub" fontfile-ffs-eldoc-obarray) "")
(set (intern "SelectChanged" fontfile-ffs-eldoc-obarray) "")
(set (intern "SelectFewer" fontfile-ffs-eldoc-obarray) "")
(set (intern "SelectFewerSingletons" fontfile-ffs-eldoc-obarray) "")
(set (intern "SelectHintingNeeded" fontfile-ffs-eldoc-obarray) "")
(set (intern "SelectIf" fontfile-ffs-eldoc-obarray) "")
(set (intern "SelectInvert" fontfile-ffs-eldoc-obarray) "")
(set (intern "SelectMore" fontfile-ffs-eldoc-obarray) "")
(set (intern "SelectMoreIf" fontfile-ffs-eldoc-obarray) "")
(set (intern "SelectMoreSingletons" fontfile-ffs-eldoc-obarray) "")
(set (intern "SelectMoreSingletonsIf" fontfile-ffs-eldoc-obarray) "")
(set (intern "SelectNone" fontfile-ffs-eldoc-obarray) "")
(set (intern "SelectSingletons" fontfile-ffs-eldoc-obarray) "")
(set (intern "SelectSingletonsIf" fontfile-ffs-eldoc-obarray) "")
(set (intern "SelectWorthOutputting" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddAccent" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddExtrema" fontfile-ffs-eldoc-obarray) "")
(set (intern "ApplySubstitution" fontfile-ffs-eldoc-obarray) "")
(set (intern "AutoTrace" fontfile-ffs-eldoc-obarray) "")
(set (intern "BitmapsAvail" fontfile-ffs-eldoc-obarray) "")
(set (intern "BitmapsRegen" fontfile-ffs-eldoc-obarray) "")
(set (intern "BuildAccented" fontfile-ffs-eldoc-obarray) "")
(set (intern "BuildComposite" fontfile-ffs-eldoc-obarray) "")
(set (intern "BuildDuplicate" fontfile-ffs-eldoc-obarray) "")
(set (intern "CanonicalContours" fontfile-ffs-eldoc-obarray) "")
(set (intern "CanonicalStart" fontfile-ffs-eldoc-obarray) "")
(set (intern "CompareFonts" fontfile-ffs-eldoc-obarray) "")
(set (intern "CompareGlyphs" fontfile-ffs-eldoc-obarray) "")
(set (intern "CorrectDirection" fontfile-ffs-eldoc-obarray) "")
(set (intern "DefaultRoundToGrid" fontfile-ffs-eldoc-obarray) "")
(set (intern "DefaultUseMyMetrics" fontfile-ffs-eldoc-obarray) "")
(set (intern "ExpandStroke" fontfile-ffs-eldoc-obarray) "")
(set (intern "FindIntersections" fontfile-ffs-eldoc-obarray) "")
(set (intern "HFlip" fontfile-ffs-eldoc-obarray) "")
(set (intern "Inline" fontfile-ffs-eldoc-obarray) "")
(set (intern "InterpolateFonts" fontfile-ffs-eldoc-obarray) "")
(set (intern "MergeFonts" fontfile-ffs-eldoc-obarray) "")
(set (intern "Move" fontfile-ffs-eldoc-obarray) "")
(set (intern "MoveReference" fontfile-ffs-eldoc-obarray) "")
(set (intern "NearlyHvCps" fontfile-ffs-eldoc-obarray) "")
(set (intern "NearlyHvLines" fontfile-ffs-eldoc-obarray) "")
(set (intern "NearlyLines" fontfile-ffs-eldoc-obarray) "")
(set (intern "NonLinearTransform" fontfile-ffs-eldoc-obarray) "")
(set (intern "Outline" fontfile-ffs-eldoc-obarray) "")
(set (intern "OverlapIntersect" fontfile-ffs-eldoc-obarray) "")
(set (intern "PositionReference" fontfile-ffs-eldoc-obarray) "")
(set (intern "RemoveOverlap" fontfile-ffs-eldoc-obarray) "")
(set (intern "Rotate" fontfile-ffs-eldoc-obarray) "")
(set (intern "RoundToCluster" fontfile-ffs-eldoc-obarray) "")
(set (intern "RoundToInt" fontfile-ffs-eldoc-obarray) "")
(set (intern "Scale" fontfile-ffs-eldoc-obarray) "")
(set (intern "ScaleToEm" fontfile-ffs-eldoc-obarray) "")
(set (intern "Shadow" fontfile-ffs-eldoc-obarray) "")
(set (intern "Simplify" fontfile-ffs-eldoc-obarray) "")
(set (intern "Skew" fontfile-ffs-eldoc-obarray) "")
(set (intern "Transform" fontfile-ffs-eldoc-obarray) "")
(set (intern "VFlip" fontfile-ffs-eldoc-obarray) "")
(set (intern "Wireframe" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddSizeFeature" fontfile-ffs-eldoc-obarray) "")
(set (intern "ChangePrivateEntry" fontfile-ffs-eldoc-obarray) "")
(set (intern "ClearPrivateEntry" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetFontBoundingBox" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetMaxpValue" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetOS2Value" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetPrivateEntry" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetTeXParam" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetTTFName" fontfile-ffs-eldoc-obarray) "")
(set (intern "HasPrivateEntry" fontfile-ffs-eldoc-obarray) "")
(set (intern "ScaleToEm" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetFondName" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetFontHasVerticalMetrics" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetFontNames" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetFontOrder" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetGasp" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetItalicAngle" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetMacStyle" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetMaxpValue" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetOS2Value" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetPanose" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetTeXParams" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetTTFName" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetUniqueID" fontfile-ffs-eldoc-obarray) "")
(set (intern "DrawsSomething" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetPosSub" fontfile-ffs-eldoc-obarray) "")
(set (intern "GlyphInfo" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetGlyphColor" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetGlyphComment" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetGlyphChanged" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetGlyphClass" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetGlyphName" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetUnicodeValue" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetGlyphTeX" fontfile-ffs-eldoc-obarray) "")
(set (intern "WorthOutputting" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddAnchorClass" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddAnchorPoint" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddLookup" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddLookupSubtable" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddPosSub" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddPosSub" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddPosSub" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddSizeFeature" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddATT" fontfile-ffs-eldoc-obarray) "")
(set (intern "ApplySubstitution" fontfile-ffs-eldoc-obarray) "")
(set (intern "CheckForAnchorClass" fontfile-ffs-eldoc-obarray) "")
(set (intern "DefaultATT" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetAnchorPoints" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetLookupInfo" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetLookups" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetLookupSubtables" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetLookupOfSubtable" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetPosSub" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetSubtableOfAnchor" fontfile-ffs-eldoc-obarray) "")
(set (intern "GenerateFeatureFile" fontfile-ffs-eldoc-obarray) "")
(set (intern "HasPreservedTable" fontfile-ffs-eldoc-obarray) "")
(set (intern "LoadTableFromFile" fontfile-ffs-eldoc-obarray) "")
(set (intern "LookupStoreLigatureInAfm" fontfile-ffs-eldoc-obarray) "")
(set (intern "LookupSetFeatureList" fontfile-ffs-eldoc-obarray) "")
(set (intern "MergeLookups" fontfile-ffs-eldoc-obarray) "")
(set (intern "MergeLookupSubtables" fontfile-ffs-eldoc-obarray) "")
(set (intern "RemoveATT" fontfile-ffs-eldoc-obarray) "")
(set (intern "RemoveAnchorClass" fontfile-ffs-eldoc-obarray) "")
(set (intern "RemoveLookup" fontfile-ffs-eldoc-obarray) "")
(set (intern "RemoveLookupSubtable" fontfile-ffs-eldoc-obarray) "")
(set (intern "RemovePosSub" fontfile-ffs-eldoc-obarray) "")
(set (intern "RemovePreservedTable" fontfile-ffs-eldoc-obarray) "")
(set (intern "SaveTableToFile" fontfile-ffs-eldoc-obarray) "")
(set (intern "CharCnt" fontfile-ffs-eldoc-obarray) "")
(set (intern "DetachGlyphs" fontfile-ffs-eldoc-obarray) "")
(set (intern "DetachAndRemoveGlyphs" fontfile-ffs-eldoc-obarray) "")
(set (intern "LoadEncodingFile" fontfile-ffs-eldoc-obarray) "")
(set (intern "MultipleEncodingsToReferences" fontfile-ffs-eldoc-obarray) "")
(set (intern "Reencode" fontfile-ffs-eldoc-obarray) "")
(set (intern "RemoveDetachedGlyphs" fontfile-ffs-eldoc-obarray) "")
(set (intern "RenameGlyphs" fontfile-ffs-eldoc-obarray) "")
(set (intern "SameGlyphAs" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetCharCnt" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddDHint" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddHHint" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddInstrs" fontfile-ffs-eldoc-obarray) "")
(set (intern "AddVHint" fontfile-ffs-eldoc-obarray) "")
(set (intern "AutoCounter" fontfile-ffs-eldoc-obarray) "")
(set (intern "AutoHint" fontfile-ffs-eldoc-obarray) "")
(set (intern "AutoInstr" fontfile-ffs-eldoc-obarray) "")
(set (intern "ChangePrivateEntry" fontfile-ffs-eldoc-obarray) "")
(set (intern "ClearGlyphCounterMasks" fontfile-ffs-eldoc-obarray) "")
(set (intern "ClearHints" fontfile-ffs-eldoc-obarray) "")
(set (intern "ClearInstrs" fontfile-ffs-eldoc-obarray) "")
(set (intern "ClearPrivateEntry" fontfile-ffs-eldoc-obarray) "")
(set (intern "ClearTable" fontfile-ffs-eldoc-obarray) "")
(set (intern "DontAutoHint" fontfile-ffs-eldoc-obarray) "")
(set (intern "FindOrAddCvtIndex" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetCvtAt" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetPrivateEntry" fontfile-ffs-eldoc-obarray) "")
(set (intern "HasPrivateEntry" fontfile-ffs-eldoc-obarray) "")
(set (intern "ReplaceGlyphCounterMasks" fontfile-ffs-eldoc-obarray) "")
(set (intern "ReplaceCvtAt" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetGlyphCounterMask" fontfile-ffs-eldoc-obarray) "")
(set (intern "SubstitutionPoints" fontfile-ffs-eldoc-obarray) "")
(set (intern "AutoKern" fontfile-ffs-eldoc-obarray) "")
(set (intern "AutoWidth" fontfile-ffs-eldoc-obarray) "")
(set (intern "CenterInWidth" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetKern" fontfile-ffs-eldoc-obarray) "")
(set (intern "RemoveAllKerns" fontfile-ffs-eldoc-obarray) "")
(set (intern "RemoveAllVKerns" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetLBearing" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetRBearing" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetVKern" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetVWidth" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetWidth" fontfile-ffs-eldoc-obarray) "")
(set (intern "VKernFromHKern" fontfile-ffs-eldoc-obarray) "")
(set (intern "MMAxisBounds" fontfile-ffs-eldoc-obarray) "")
(set (intern "MMAxisNames" fontfile-ffs-eldoc-obarray) "")
(set (intern "MMBlendToNewFont" fontfile-ffs-eldoc-obarray) "")
(set (intern "MMChangeInstance" fontfile-ffs-eldoc-obarray) "")
(set (intern "MMChangeWeight" fontfile-ffs-eldoc-obarray) "")
(set (intern "MMInstanceNames" fontfile-ffs-eldoc-obarray) "")
(set (intern "MMWeightedName" fontfile-ffs-eldoc-obarray) "")
(set (intern "CIDChangeSubFont" fontfile-ffs-eldoc-obarray) "")
(set (intern "CIDFlatten" fontfile-ffs-eldoc-obarray) "")
(set (intern "CIDFlattenByCMap" fontfile-ffs-eldoc-obarray) "")
(set (intern "CIDSetFontNames" fontfile-ffs-eldoc-obarray) "")
(set (intern "ConvertToCID" fontfile-ffs-eldoc-obarray) "")
(set (intern "ConvertByCMap" fontfile-ffs-eldoc-obarray) "")
(set (intern "PreloadCidmap" fontfile-ffs-eldoc-obarray) "")
(set (intern "AskUser" fontfile-ffs-eldoc-obarray) "")
(set (intern "Error" fontfile-ffs-eldoc-obarray) "")
(set (intern "PostNotice" fontfile-ffs-eldoc-obarray) "")
(set (intern "Print" fontfile-ffs-eldoc-obarray) "")
(set (intern "DefaultOtherSubrs" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetPref" fontfile-ffs-eldoc-obarray) "")
(set (intern "LoadEncodingFile" fontfile-ffs-eldoc-obarray) "")
(set (intern "LoadNamelist" fontfile-ffs-eldoc-obarray) "")
(set (intern "LoadNamelistDir" fontfile-ffs-eldoc-obarray) "")
(set (intern "LoadPlugin" fontfile-ffs-eldoc-obarray) "")
(set (intern "LoadPluginDir" fontfile-ffs-eldoc-obarray) "")
(set (intern "LoadPrefs" fontfile-ffs-eldoc-obarray) "")
(set (intern "ReadOtherSubrsFile" fontfile-ffs-eldoc-obarray) "")
(set (intern "SavePrefs" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetPref" fontfile-ffs-eldoc-obarray) "")
(set (intern "ATan2" fontfile-ffs-eldoc-obarray) "")
(set (intern "Ceil" fontfile-ffs-eldoc-obarray) "")
(set (intern "Chr" fontfile-ffs-eldoc-obarray) "")
(set (intern "Cos" fontfile-ffs-eldoc-obarray) "")
(set (intern "Exp" fontfile-ffs-eldoc-obarray) "")
(set (intern "Floor" fontfile-ffs-eldoc-obarray) "")
(set (intern "Int" fontfile-ffs-eldoc-obarray) "")
(set (intern "IsFinite" fontfile-ffs-eldoc-obarray) "")
(set (intern "IsNan" fontfile-ffs-eldoc-obarray) "")
(set (intern "Log" fontfile-ffs-eldoc-obarray) "")
(set (intern "Ord" fontfile-ffs-eldoc-obarray) "")
(set (intern "Pow" fontfile-ffs-eldoc-obarray) "")
(set (intern "Rand" fontfile-ffs-eldoc-obarray) "")
(set (intern "Real" fontfile-ffs-eldoc-obarray) "")
(set (intern "Round" fontfile-ffs-eldoc-obarray) "")
(set (intern "Sin" fontfile-ffs-eldoc-obarray) "")
(set (intern "Sqrt" fontfile-ffs-eldoc-obarray) "")
(set (intern "Strskipint" fontfile-ffs-eldoc-obarray) "")
(set (intern "Strtod" fontfile-ffs-eldoc-obarray) "")
(set (intern "Strtol" fontfile-ffs-eldoc-obarray) "")
(set (intern "Tan" fontfile-ffs-eldoc-obarray) "")
(set (intern "ToString" fontfile-ffs-eldoc-obarray) "")
(set (intern "UCodePoint" fontfile-ffs-eldoc-obarray) "")
(set (intern "NameFromUnicode" fontfile-ffs-eldoc-obarray) "")
(set (intern "UCodePoint" fontfile-ffs-eldoc-obarray) "")
(set (intern "UnicodeFromName" fontfile-ffs-eldoc-obarray) "")
(set (intern "Ucs4" fontfile-ffs-eldoc-obarray) "")
(set (intern "Utf8" fontfile-ffs-eldoc-obarray) "")
(set (intern "Chr" fontfile-ffs-eldoc-obarray) "")
(set (intern "GetEnv" fontfile-ffs-eldoc-obarray) "")
(set (intern "NameFromUnicode" fontfile-ffs-eldoc-obarray) "")
(set (intern "Ord" fontfile-ffs-eldoc-obarray) "")
(set (intern "Strcasecmp" fontfile-ffs-eldoc-obarray) "")
(set (intern "Strcasestr" fontfile-ffs-eldoc-obarray) "")
(set (intern "Strftime" fontfile-ffs-eldoc-obarray) "")
(set (intern "StrJoin" fontfile-ffs-eldoc-obarray) "")
(set (intern "Strlen" fontfile-ffs-eldoc-obarray) "")
(set (intern "Strrstr" fontfile-ffs-eldoc-obarray) "")
(set (intern "Strskipint" fontfile-ffs-eldoc-obarray) "")
(set (intern "StrSplit" fontfile-ffs-eldoc-obarray) "")
(set (intern "Strstr" fontfile-ffs-eldoc-obarray) "")
(set (intern "Strsub" fontfile-ffs-eldoc-obarray) "")
(set (intern "Strtod" fontfile-ffs-eldoc-obarray) "")
(set (intern "Strtol" fontfile-ffs-eldoc-obarray) "")
(set (intern "ToString" fontfile-ffs-eldoc-obarray) "")
(set (intern "UnicodeFromName" fontfile-ffs-eldoc-obarray) "")
(set (intern "Ucs4" fontfile-ffs-eldoc-obarray) "")
(set (intern "Utf8" fontfile-ffs-eldoc-obarray) "")
(set (intern "IsAlNum" fontfile-ffs-eldoc-obarray) "")
(set (intern "IsAlpha" fontfile-ffs-eldoc-obarray) "")
(set (intern "IsDigit" fontfile-ffs-eldoc-obarray) "")
(set (intern "IsHexDigit" fontfile-ffs-eldoc-obarray) "")
(set (intern "IsLower" fontfile-ffs-eldoc-obarray) "")
(set (intern "IsSpace" fontfile-ffs-eldoc-obarray) "")
(set (intern "IsUpper" fontfile-ffs-eldoc-obarray) "")
(set (intern "ToLower" fontfile-ffs-eldoc-obarray) "")
(set (intern "ToMirror" fontfile-ffs-eldoc-obarray) "")
(set (intern "ToUpper" fontfile-ffs-eldoc-obarray) "")
(set (intern "Array" fontfile-ffs-eldoc-obarray) "")
(set (intern "SizeOf" fontfile-ffs-eldoc-obarray) "")
(set (intern "InFont" fontfile-ffs-eldoc-obarray) "")
(set (intern "TypeOf" fontfile-ffs-eldoc-obarray) "")
(set (intern "ClearCharCounterMasks" fontfile-ffs-eldoc-obarray) "")
(set (intern "CharInfo" fontfile-ffs-eldoc-obarray) "")
(set (intern "ReplaceCharCounterMasks" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetCharColor" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetCharComment" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetCharCounterMask" fontfile-ffs-eldoc-obarray) "")
(set (intern "SetCharName" fontfile-ffs-eldoc-obarray) "")

(defun fontfile-ffs-eldoc-function ()
    "Returns a doc string appropriate for the current context, or nil."
    (symbol-value (intern-soft (thing-at-point 'symbol)
                               fontfile-ffs-eldoc-obarray)))
