(require 'thingatpt)
(require 'eldoc)
(setq eldoc-documentation-function 'fontfile-ttx-eldoc-function)

(setq fontfile-ttx-eldoc-obarray (make-vector 721 0))

(set (intern "avar" fontfile-ttx-eldoc-obarray) "Axis variation.")
(set (intern "acnt" fontfile-ttx-eldoc-obarray) "Accent attachment.")
(set (intern "ankr" fontfile-ttx-eldoc-obarray) "Anchor point.")
(set (intern "avar" fontfile-ttx-eldoc-obarray) "Axis variation.")
(set (intern "BASE" fontfile-ttx-eldoc-obarray) "Baseline data.")
(set (intern "bdat" fontfile-ttx-eldoc-obarray) "Bitmap data.")
(set (intern "BDF" fontfile-ttx-eldoc-obarray) "X11 BDF header.")
(set (intern "bhed" fontfile-ttx-eldoc-obarray) "Bitmap font header.")
(set (intern "bloc" fontfile-ttx-eldoc-obarray) "Bitmap location data.")
(set (intern "bsln" fontfile-ttx-eldoc-obarray) "Baseline data.")
(set (intern "CBDT" fontfile-ttx-eldoc-obarray) "Color bitmap data.")
(set (intern "CBLC" fontfile-ttx-eldoc-obarray) "Color bitmap location data.")
(set (intern "CFF" fontfile-ttx-eldoc-obarray) "Compact Font Format.")
(set (intern "cmap" fontfile-ttx-eldoc-obarray) "Character to glyph mapping.")
(set (intern "COLR" fontfile-ttx-eldoc-obarray) "Color table.")
(set (intern "CPAL" fontfile-ttx-eldoc-obarray) "Color palette table.")
(set (intern "cvar" fontfile-ttx-eldoc-obarray) "Variations on CVT table.")
(set (intern "cvt" fontfile-ttx-eldoc-obarray) "Control value table.")
(set (intern "DSIG" fontfile-ttx-eldoc-obarray) "Digital signature.")
(set (intern "EBDT" fontfile-ttx-eldoc-obarray) "Embedded bitmap data.")
(set (intern "EBLC" fontfile-ttx-eldoc-obarray) "Embedded bitmap location.")
(set (intern "EBSC" fontfile-ttx-eldoc-obarray) "Embedded bitmap scaling control.")
(set (intern "fdsc" fontfile-ttx-eldoc-obarray) "Font descriptor.")
(set (intern "feat" fontfile-ttx-eldoc-obarray) "Layout feature table.")
(set (intern "FFTM" fontfile-ttx-eldoc-obarray) "FontForge timestamp.")
(set (intern "fmtx" fontfile-ttx-eldoc-obarray) "Font metrics.")
(set (intern "fond" fontfile-ttx-eldoc-obarray) "Font family compatibility.")
(set (intern "fpgm" fontfile-ttx-eldoc-obarray) "Font program.")
(set (intern "fvar" fontfile-ttx-eldoc-obarray) "Font variation.")
(set (intern "gasp" fontfile-ttx-eldoc-obarray) "Grid-fitting and scan-conversion procedure.")
(set (intern "gasp" fontfile-ttx-eldoc-obarray) "Grid-fitting/Scan-conversion (optional table).")
(set (intern "GDEF" fontfile-ttx-eldoc-obarray) "Glyph definition data.")
(set (intern "Glat" fontfile-ttx-eldoc-obarray) "Glyph attributes table.")
(set (intern "Gloc" fontfile-ttx-eldoc-obarray) "Indexes for Glat table.")
(set (intern "glyf" fontfile-ttx-eldoc-obarray) "Glyph outline.")
(set (intern "GPOS" fontfile-ttx-eldoc-obarray) "Glyph positioning data.")
(set (intern "GSUB" fontfile-ttx-eldoc-obarray) "Glyph substitution data.")
(set (intern "gvar" fontfile-ttx-eldoc-obarray) "Glyph variation.")
(set (intern "hdmx" fontfile-ttx-eldoc-obarray) "Horizontal device metrics.")
(set (intern "head" fontfile-ttx-eldoc-obarray) "Font header.")
(set (intern "hhea" fontfile-ttx-eldoc-obarray) "Horizontal header.")
(set (intern "hmtx" fontfile-ttx-eldoc-obarray) "Horizontal metrics.")
(set (intern "JSTF" fontfile-ttx-eldoc-obarray) "Justification data.")
(set (intern "just" fontfile-ttx-eldoc-obarray) "Justification.")
(set (intern "kern" fontfile-ttx-eldoc-obarray) "Kerning.")
(set (intern "kerx" fontfile-ttx-eldoc-obarray) "Extended kerning.")
(set (intern "lcar" fontfile-ttx-eldoc-obarray) "Ligature caret.")
(set (intern "loca" fontfile-ttx-eldoc-obarray) "Glyph location.")
(set (intern "ltag" fontfile-ttx-eldoc-obarray) "Language tag.")
(set (intern "LTSH" fontfile-ttx-eldoc-obarray) "Linear threshold data.")
(set (intern "MATH" fontfile-ttx-eldoc-obarray) "Mathematical typesetting.")
(set (intern "maxp" fontfile-ttx-eldoc-obarray) "Maximum profile.")
(set (intern "meta" fontfile-ttx-eldoc-obarray) "Metadata.")
(set (intern "mort" fontfile-ttx-eldoc-obarray) "Metamorphosis (deprecated).")
(set (intern "morx" fontfile-ttx-eldoc-obarray) "Extended metamorphosis.")
(set (intern "name" fontfile-ttx-eldoc-obarray) "Name.")
(set (intern "opbd" fontfile-ttx-eldoc-obarray) "Optical bounds.")
(set (intern "OS/2" fontfile-ttx-eldoc-obarray) "OS/2 and Windows specific metrics.")
(set (intern "PCLT" fontfile-ttx-eldoc-obarray) "PCL 5 data.")
(set (intern "PfEd" fontfile-ttx-eldoc-obarray) "FontForge's personal table.")
(set (intern "post" fontfile-ttx-eldoc-obarray) "Glyph name and PostScript compatibility.")
(set (intern "prep" fontfile-ttx-eldoc-obarray) "Control value program.")
(set (intern "prop" fontfile-ttx-eldoc-obarray) "Glyph properties.")
(set (intern "sbix" fontfile-ttx-eldoc-obarray) "Extended bitmaps.")
(set (intern "Silf" fontfile-ttx-eldoc-obarray) "Main logic, including finite state machine for rule matching, constraints, and rule action code.")
(set (intern "Sill" fontfile-ttx-eldoc-obarray) "Language table, containing mappings between language codes and features.")
(set (intern "SVG" fontfile-ttx-eldoc-obarray) "The SVG (Scalable Vector Graphics) table.")
(set (intern "TeX" fontfile-ttx-eldoc-obarray) "TeX information.")
(set (intern "trak" fontfile-ttx-eldoc-obarray) "Tracking.")
(set (intern "VDMX" fontfile-ttx-eldoc-obarray) "Vertical device metrics.")
(set (intern "vhea" fontfile-ttx-eldoc-obarray) "Vertical Metrics header.")
(set (intern "vmtx" fontfile-ttx-eldoc-obarray) "Vertical Metrics.")
(set (intern "VORG" fontfile-ttx-eldoc-obarray) "Vertical Origin (optional table).")
(set (intern "xref" fontfile-ttx-eldoc-obarray) "Cross-reference.")
(set (intern "Zapf" fontfile-ttx-eldoc-obarray) "Glyph reference.")
(set (intern "aalt" fontfile-ttx-eldoc-obarray) "Access All Alternates")
(set (intern "abvf" fontfile-ttx-eldoc-obarray) "Above-base Forms")
(set (intern "abvm" fontfile-ttx-eldoc-obarray) "Above-base Mark Positioning")
(set (intern "abvs" fontfile-ttx-eldoc-obarray) "Above-base Substitutions")
(set (intern "afrc" fontfile-ttx-eldoc-obarray) "Alternative Fractions")
(set (intern "akhn" fontfile-ttx-eldoc-obarray) "Akhands")
(set (intern "blwf" fontfile-ttx-eldoc-obarray) "Below-base Forms")
(set (intern "blwm" fontfile-ttx-eldoc-obarray) "Below-base Mark Positioning")
(set (intern "blws" fontfile-ttx-eldoc-obarray) "Below-base Substitutions")
(set (intern "calt" fontfile-ttx-eldoc-obarray) "Contextual Alternates")
(set (intern "case" fontfile-ttx-eldoc-obarray) "Case-Sensitive Forms")
(set (intern "ccmp" fontfile-ttx-eldoc-obarray) "Glyph Composition / Decomposition")
(set (intern "cfar" fontfile-ttx-eldoc-obarray) "Conjunct Form After Ro")
(set (intern "cjct" fontfile-ttx-eldoc-obarray) "Conjunct Forms")
(set (intern "clig" fontfile-ttx-eldoc-obarray) "Contextual Ligatures")
(set (intern "cpct" fontfile-ttx-eldoc-obarray) "Centered CJK Punctuation")
(set (intern "cpsp" fontfile-ttx-eldoc-obarray) "Capital Spacing")
(set (intern "cswh" fontfile-ttx-eldoc-obarray) "Contextual Swash")
(set (intern "curs" fontfile-ttx-eldoc-obarray) "Cursive Positioning")
(set (intern "cv01" fontfile-ttx-eldoc-obarray) "Character Variants")
;; Need cv02 through cv99?
(set (intern "c2pc" fontfile-ttx-eldoc-obarray) "Petite Capitals From Capitals")
(set (intern "c2sc" fontfile-ttx-eldoc-obarray) "Small Capitals From Capitals")
(set (intern "dist" fontfile-ttx-eldoc-obarray) "Distances")
(set (intern "dlig" fontfile-ttx-eldoc-obarray) "Discretionary Ligatures")
(set (intern "dnom" fontfile-ttx-eldoc-obarray) "Denominators")
(set (intern "expt" fontfile-ttx-eldoc-obarray) "Expert Forms")
(set (intern "falt" fontfile-ttx-eldoc-obarray) "Final Glyph on Line Alternates")
(set (intern "fin2" fontfile-ttx-eldoc-obarray) "Terminal Forms #2")
(set (intern "fin3" fontfile-ttx-eldoc-obarray) "Terminal Forms #3")
(set (intern "fina" fontfile-ttx-eldoc-obarray) "Terminal Forms")
(set (intern "frac" fontfile-ttx-eldoc-obarray) "Fractions")
(set (intern "fwid" fontfile-ttx-eldoc-obarray) "Full Widths")
(set (intern "half" fontfile-ttx-eldoc-obarray) "Half Forms")
(set (intern "haln" fontfile-ttx-eldoc-obarray) "Halant Forms")
(set (intern "halt" fontfile-ttx-eldoc-obarray) "Alternate Half Widths")
(set (intern "hist" fontfile-ttx-eldoc-obarray) "Historical Forms")
(set (intern "hkna" fontfile-ttx-eldoc-obarray) "Horizontal Kana Alternates")
(set (intern "hlig" fontfile-ttx-eldoc-obarray) "Historical Ligatures")
(set (intern "hngl" fontfile-ttx-eldoc-obarray) "Hangul")
(set (intern "hojo" fontfile-ttx-eldoc-obarray) "Hojo Kanji Forms (JIS X 0212-1990 Kanji Forms)")
(set (intern "hwid" fontfile-ttx-eldoc-obarray) "Half Widths")
(set (intern "init" fontfile-ttx-eldoc-obarray) "Initial Forms")
(set (intern "isol" fontfile-ttx-eldoc-obarray) "Isolated Forms")
(set (intern "ital" fontfile-ttx-eldoc-obarray) "Italics")
(set (intern "jalt" fontfile-ttx-eldoc-obarray) "Justification Alternates")
(set (intern "jp78" fontfile-ttx-eldoc-obarray) "JIS78 Forms")
(set (intern "jp83" fontfile-ttx-eldoc-obarray) "JIS83 Forms")
(set (intern "jp90" fontfile-ttx-eldoc-obarray) "JIS90 Forms")
(set (intern "jp04" fontfile-ttx-eldoc-obarray) "JIS2004 Forms")
(set (intern "kern" fontfile-ttx-eldoc-obarray) "Kerning")
(set (intern "lfbd" fontfile-ttx-eldoc-obarray) "Left Bounds")
(set (intern "liga" fontfile-ttx-eldoc-obarray) "Standard Ligatures")
(set (intern "ljmo" fontfile-ttx-eldoc-obarray) "Leading Jamo Forms")
(set (intern "lnum" fontfile-ttx-eldoc-obarray) "Lining Figures")
(set (intern "locl" fontfile-ttx-eldoc-obarray) "Localized Forms")
(set (intern "ltra" fontfile-ttx-eldoc-obarray) "Left-to-right alternates")
(set (intern "ltrm" fontfile-ttx-eldoc-obarray) "Left-to-right mirrored forms")
(set (intern "mark" fontfile-ttx-eldoc-obarray) "Mark Positioning")
(set (intern "med2" fontfile-ttx-eldoc-obarray) "Medial Forms #2")
(set (intern "medi" fontfile-ttx-eldoc-obarray) "Medial Forms")
(set (intern "mgrk" fontfile-ttx-eldoc-obarray) "Mathematical Greek")
(set (intern "mkmk" fontfile-ttx-eldoc-obarray) "Mark to Mark Positioning")
(set (intern "mset" fontfile-ttx-eldoc-obarray) "Mark Positioning via Substitution")
(set (intern "nalt" fontfile-ttx-eldoc-obarray) "Alternate Annotation Forms")
(set (intern "nlck" fontfile-ttx-eldoc-obarray) "NLC Kanji Forms")
(set (intern "nukt" fontfile-ttx-eldoc-obarray) "Nukta Forms")
(set (intern "numr" fontfile-ttx-eldoc-obarray) "Numerators")
(set (intern "onum" fontfile-ttx-eldoc-obarray) "Oldstyle Figures")
(set (intern "opbd" fontfile-ttx-eldoc-obarray) "Optical Bounds")
(set (intern "ordn" fontfile-ttx-eldoc-obarray) "Ordinals")
(set (intern "ornm" fontfile-ttx-eldoc-obarray) "Ornaments")
(set (intern "palt" fontfile-ttx-eldoc-obarray) "Proportional Alternate Widths")
(set (intern "pcap" fontfile-ttx-eldoc-obarray) "Petite Capitals")
(set (intern "pkna" fontfile-ttx-eldoc-obarray) "Proportional Kana")
(set (intern "pnum" fontfile-ttx-eldoc-obarray) "Proportional Figures")
(set (intern "pref" fontfile-ttx-eldoc-obarray) "Pre-Base Forms")
(set (intern "pres" fontfile-ttx-eldoc-obarray) "Pre-base Substitutions")
(set (intern "pstf" fontfile-ttx-eldoc-obarray) "Post-base Forms")
(set (intern "psts" fontfile-ttx-eldoc-obarray) "Post-base Substitutions")
(set (intern "pwid" fontfile-ttx-eldoc-obarray) "Proportional Widths")
(set (intern "qwid" fontfile-ttx-eldoc-obarray) "Quarter Widths")
(set (intern "rand" fontfile-ttx-eldoc-obarray) "Randomize")
(set (intern "rkrf" fontfile-ttx-eldoc-obarray) "Rakar Forms")
(set (intern "rlig" fontfile-ttx-eldoc-obarray) "Required Ligatures")
(set (intern "rphf" fontfile-ttx-eldoc-obarray) "Reph Forms")
(set (intern "rtbd" fontfile-ttx-eldoc-obarray) "Right Bounds")
(set (intern "rtla" fontfile-ttx-eldoc-obarray) "Right-to-left alternates")
(set (intern "rtlm" fontfile-ttx-eldoc-obarray) "Right-to-left mirrored forms")
(set (intern "ruby" fontfile-ttx-eldoc-obarray) "Ruby Notation Forms")
(set (intern "salt" fontfile-ttx-eldoc-obarray) "Stylistic Alternates")
(set (intern "sinf" fontfile-ttx-eldoc-obarray) "Scientific Inferiors")
(set (intern "size" fontfile-ttx-eldoc-obarray) "Optical size")
(set (intern "smcp" fontfile-ttx-eldoc-obarray) "Small Capitals")
(set (intern "smpl" fontfile-ttx-eldoc-obarray) "Simplified Forms")
(set (intern "ss01" fontfile-ttx-eldoc-obarray) "Stylistic Set 1")
(set (intern "ss02" fontfile-ttx-eldoc-obarray) "Stylistic Set 2")
(set (intern "ss03" fontfile-ttx-eldoc-obarray) "Stylistic Set 3")
(set (intern "ss04" fontfile-ttx-eldoc-obarray) "Stylistic Set 4")
(set (intern "ss05" fontfile-ttx-eldoc-obarray) "Stylistic Set 5")
(set (intern "ss06" fontfile-ttx-eldoc-obarray) "Stylistic Set 6")
(set (intern "ss07" fontfile-ttx-eldoc-obarray) "Stylistic Set 7")
(set (intern "ss08" fontfile-ttx-eldoc-obarray) "Stylistic Set 8")
(set (intern "ss09" fontfile-ttx-eldoc-obarray) "Stylistic Set 9")
(set (intern "ss10" fontfile-ttx-eldoc-obarray) "Stylistic Set 10")
(set (intern "ss11" fontfile-ttx-eldoc-obarray) "Stylistic Set 11")
(set (intern "ss12" fontfile-ttx-eldoc-obarray) "Stylistic Set 12")
(set (intern "ss13" fontfile-ttx-eldoc-obarray) "Stylistic Set 13")
(set (intern "ss14" fontfile-ttx-eldoc-obarray) "Stylistic Set 14")
(set (intern "ss15" fontfile-ttx-eldoc-obarray) "Stylistic Set 15")
(set (intern "ss16" fontfile-ttx-eldoc-obarray) "Stylistic Set 16")
(set (intern "ss17" fontfile-ttx-eldoc-obarray) "Stylistic Set 17")
(set (intern "ss18" fontfile-ttx-eldoc-obarray) "Stylistic Set 18")
(set (intern "ss19" fontfile-ttx-eldoc-obarray) "Stylistic Set 19")
(set (intern "ss20" fontfile-ttx-eldoc-obarray) "Stylistic Set 20")
(set (intern "subs" fontfile-ttx-eldoc-obarray) "Subscript")
(set (intern "sups" fontfile-ttx-eldoc-obarray) "Superscript")
(set (intern "swsh" fontfile-ttx-eldoc-obarray) "Swash")
(set (intern "titl" fontfile-ttx-eldoc-obarray) "Titling")
(set (intern "tjmo" fontfile-ttx-eldoc-obarray) "Trailing Jamo Forms")
(set (intern "tnam" fontfile-ttx-eldoc-obarray) "Traditional Name Forms")
(set (intern "tnum" fontfile-ttx-eldoc-obarray) "Tabular Figures")
(set (intern "trad" fontfile-ttx-eldoc-obarray) "Traditional Forms")
(set (intern "twid" fontfile-ttx-eldoc-obarray) "Third Widths")
(set (intern "unic" fontfile-ttx-eldoc-obarray) "Unicase")
(set (intern "valt" fontfile-ttx-eldoc-obarray) "Alternate Vertical Metrics")
(set (intern "vatu" fontfile-ttx-eldoc-obarray) "Vattu Variants")
(set (intern "vert" fontfile-ttx-eldoc-obarray) "Vertical Writing")
(set (intern "vhal" fontfile-ttx-eldoc-obarray) "Alternate Vertical Half Metrics")
(set (intern "vjmo" fontfile-ttx-eldoc-obarray) "Vowel Jamo Forms")
(set (intern "vkna" fontfile-ttx-eldoc-obarray) "Vertical Kana Alternates")
(set (intern "vkrn" fontfile-ttx-eldoc-obarray) "Vertical Kerning")
(set (intern "vpal" fontfile-ttx-eldoc-obarray) "Proportional Alternate Vertical Metrics")
(set (intern "vrt2" fontfile-ttx-eldoc-obarray) "Vertical Alternates and Rotation")
(set (intern "zero" fontfile-ttx-eldoc-obarray) "Slashed Zero")
(set (intern "hang" fontfile-ttx-eldoc-obarray) "hanging baseline")
(set (intern "icfb" fontfile-ttx-eldoc-obarray) "ideographic character face bottom edge baseline")
(set (intern "icft" fontfile-ttx-eldoc-obarray) "ideographic character face top edge baseline")
(set (intern "ideo" fontfile-ttx-eldoc-obarray) "ideographic em-box bottom edge baseline")
(set (intern "idtp" fontfile-ttx-eldoc-obarray) "ideographic em-box top edge baseline")
(set (intern "math" fontfile-ttx-eldoc-obarray) "baseline for mathematical expressions")
(set (intern "romn" fontfile-ttx-eldoc-obarray) "baseline for alphabetic scripts")
(set (intern "ABA" fontfile-ttx-eldoc-obarray) "Abaza")
(set (intern "ABK" fontfile-ttx-eldoc-obarray) "Abkhazian")
(set (intern "ADY" fontfile-ttx-eldoc-obarray) "Adyghe")
(set (intern "AFK" fontfile-ttx-eldoc-obarray) "Afrikaans")
(set (intern "AFR" fontfile-ttx-eldoc-obarray) "Afar")
(set (intern "AGW" fontfile-ttx-eldoc-obarray) "Agaw")
(set (intern "ALS" fontfile-ttx-eldoc-obarray) "Alsatian")
(set (intern "ALT" fontfile-ttx-eldoc-obarray) "Altai")
(set (intern "AMH" fontfile-ttx-eldoc-obarray) "Amharic")
(set (intern "APPH" fontfile-ttx-eldoc-obarray) "Phonetic transcription—Americanist conventions")
(set (intern "ARA" fontfile-ttx-eldoc-obarray) "Arabic")
(set (intern "ARI" fontfile-ttx-eldoc-obarray) "Aari")
(set (intern "ARK" fontfile-ttx-eldoc-obarray) "Arakanese")
(set (intern "ASM" fontfile-ttx-eldoc-obarray) "Assamese")
(set (intern "ATH" fontfile-ttx-eldoc-obarray) "Athapaskan")
(set (intern "AVR" fontfile-ttx-eldoc-obarray) "Avar")
(set (intern "AWA" fontfile-ttx-eldoc-obarray) "Awadhi")
(set (intern "AYM" fontfile-ttx-eldoc-obarray) "Aymara")
(set (intern "AZE" fontfile-ttx-eldoc-obarray) "Azeri")
(set (intern "BAD" fontfile-ttx-eldoc-obarray) "Badaga")
(set (intern "BAG" fontfile-ttx-eldoc-obarray) "Baghelkhandi")
(set (intern "BAL" fontfile-ttx-eldoc-obarray) "Balkar")
(set (intern "BAU" fontfile-ttx-eldoc-obarray) "Baule")
(set (intern "BBR" fontfile-ttx-eldoc-obarray) "Berber")
(set (intern "BCH" fontfile-ttx-eldoc-obarray) "Bench")
(set (intern "BCR" fontfile-ttx-eldoc-obarray) "Bible Cree")
(set (intern "BEL" fontfile-ttx-eldoc-obarray) "Belarussian")
(set (intern "BEM" fontfile-ttx-eldoc-obarray) "Bemba")
(set (intern "BEN" fontfile-ttx-eldoc-obarray) "Bengali")
(set (intern "BGR" fontfile-ttx-eldoc-obarray) "Bulgarian")
(set (intern "BHI" fontfile-ttx-eldoc-obarray) "Bhili")
(set (intern "BHO" fontfile-ttx-eldoc-obarray) "Bhojpuri")
(set (intern "BIK" fontfile-ttx-eldoc-obarray) "Bikol")
(set (intern "BIL" fontfile-ttx-eldoc-obarray) "Bilen")
(set (intern "BKF" fontfile-ttx-eldoc-obarray) "Blackfoot")
(set (intern "BLI" fontfile-ttx-eldoc-obarray) "Balochi")
(set (intern "BLN" fontfile-ttx-eldoc-obarray) "Balante")
(set (intern "BLT" fontfile-ttx-eldoc-obarray) "Balti")
(set (intern "BMB" fontfile-ttx-eldoc-obarray) "Bambara")
(set (intern "BML" fontfile-ttx-eldoc-obarray) "Bamileke")
(set (intern "BOS" fontfile-ttx-eldoc-obarray) "Bosnian")
(set (intern "BRE" fontfile-ttx-eldoc-obarray) "Breton")
(set (intern "BRH" fontfile-ttx-eldoc-obarray) "Brahui")
(set (intern "BRI" fontfile-ttx-eldoc-obarray) "Braj Bhasha")
(set (intern "BRM" fontfile-ttx-eldoc-obarray) "Burmese")
(set (intern "BSH" fontfile-ttx-eldoc-obarray) "Bashkir")
(set (intern "BTI" fontfile-ttx-eldoc-obarray) "Beti")
(set (intern "CAT" fontfile-ttx-eldoc-obarray) "Catalan")
(set (intern "CEB" fontfile-ttx-eldoc-obarray) "Cebuano")
(set (intern "CHE" fontfile-ttx-eldoc-obarray) "Chechen")
(set (intern "CHG" fontfile-ttx-eldoc-obarray) "Chaha Gurage")
(set (intern "CHH" fontfile-ttx-eldoc-obarray) "Chattisgarhi")
(set (intern "CHI" fontfile-ttx-eldoc-obarray) "Chichewa")
(set (intern "CHK" fontfile-ttx-eldoc-obarray) "Chukchi")
(set (intern "CHP" fontfile-ttx-eldoc-obarray) "Chipewyan")
(set (intern "CHR" fontfile-ttx-eldoc-obarray) "Cherokee")
(set (intern "CHU" fontfile-ttx-eldoc-obarray) "Chuvash")
(set (intern "CMR" fontfile-ttx-eldoc-obarray) "Comorian")
(set (intern "COP" fontfile-ttx-eldoc-obarray) "Coptic")
(set (intern "COS" fontfile-ttx-eldoc-obarray) "Corsican")
(set (intern "CRE" fontfile-ttx-eldoc-obarray) "Cree")
(set (intern "CRR" fontfile-ttx-eldoc-obarray) "Carrier")
(set (intern "CRT" fontfile-ttx-eldoc-obarray) "Crimean Tatar")
(set (intern "CSL" fontfile-ttx-eldoc-obarray) "Church Slavonic")
(set (intern "CSY" fontfile-ttx-eldoc-obarray) "Czech")
(set (intern "DAN" fontfile-ttx-eldoc-obarray) "Danish")
(set (intern "DAR" fontfile-ttx-eldoc-obarray) "Dargwa")
(set (intern "DCR" fontfile-ttx-eldoc-obarray) "Woods Cree")
(set (intern "DEU" fontfile-ttx-eldoc-obarray) "German")
(set (intern "DGR" fontfile-ttx-eldoc-obarray) "Dogri")
(set (intern "DHV" fontfile-ttx-eldoc-obarray) "Dhivehi (deprecated)")
(set (intern "DIV" fontfile-ttx-eldoc-obarray) "Dhivehi")
(set (intern "DJR" fontfile-ttx-eldoc-obarray) "Djerma")
(set (intern "DNG" fontfile-ttx-eldoc-obarray) "Dangme")
(set (intern "DNK" fontfile-ttx-eldoc-obarray) "Dinka")
(set (intern "DRI" fontfile-ttx-eldoc-obarray) "Dari")
(set (intern "DUN" fontfile-ttx-eldoc-obarray) "Dungan")
(set (intern "DZN" fontfile-ttx-eldoc-obarray) "Dzongkha")
(set (intern "EBI" fontfile-ttx-eldoc-obarray) "Ebira")
(set (intern "ECR" fontfile-ttx-eldoc-obarray) "Eastern Cree")
(set (intern "EDO" fontfile-ttx-eldoc-obarray) "Edo")
(set (intern "EFI" fontfile-ttx-eldoc-obarray) "Efik")
(set (intern "ELL" fontfile-ttx-eldoc-obarray) "Greek")
(set (intern "ENG" fontfile-ttx-eldoc-obarray) "English")
(set (intern "ERZ" fontfile-ttx-eldoc-obarray) "Erzya")
(set (intern "ESP" fontfile-ttx-eldoc-obarray) "Spanish")
(set (intern "ETI" fontfile-ttx-eldoc-obarray) "Estonian")
(set (intern "EUQ" fontfile-ttx-eldoc-obarray) "Basque")
(set (intern "EVK" fontfile-ttx-eldoc-obarray) "Evenki")
(set (intern "EVN" fontfile-ttx-eldoc-obarray) "Even")
(set (intern "EWE" fontfile-ttx-eldoc-obarray) "Ewe")
(set (intern "FAN" fontfile-ttx-eldoc-obarray) "French Antillean")
(set (intern "FAR" fontfile-ttx-eldoc-obarray) "Farsi")
(set (intern "FIN" fontfile-ttx-eldoc-obarray) "Finnish")
(set (intern "FJI" fontfile-ttx-eldoc-obarray) "Fijian")
(set (intern "FLE" fontfile-ttx-eldoc-obarray) "Flemish")
(set (intern "FNE" fontfile-ttx-eldoc-obarray) "Forest Nenets")
(set (intern "FON" fontfile-ttx-eldoc-obarray) "Fon")
(set (intern "FOS" fontfile-ttx-eldoc-obarray) "Faroese")
(set (intern "FRA" fontfile-ttx-eldoc-obarray) "French")
(set (intern "FRI" fontfile-ttx-eldoc-obarray) "Frisian")
(set (intern "FRL" fontfile-ttx-eldoc-obarray) "Friulian")
(set (intern "FTA" fontfile-ttx-eldoc-obarray) "Futa")
(set (intern "FUL" fontfile-ttx-eldoc-obarray) "Fulani")
(set (intern "GAD" fontfile-ttx-eldoc-obarray) "Ga")
(set (intern "GAE" fontfile-ttx-eldoc-obarray) "Gaelic")
(set (intern "GAG" fontfile-ttx-eldoc-obarray) "Gagauz")
(set (intern "GAL" fontfile-ttx-eldoc-obarray) "Galician")
(set (intern "GAR" fontfile-ttx-eldoc-obarray) "Garshuni")
(set (intern "GAW" fontfile-ttx-eldoc-obarray) "Garhwali")
(set (intern "GEZ" fontfile-ttx-eldoc-obarray) "Ge'ez")
(set (intern "GIL" fontfile-ttx-eldoc-obarray) "Gilyak")
(set (intern "GMZ" fontfile-ttx-eldoc-obarray) "Gumuz")
(set (intern "GON" fontfile-ttx-eldoc-obarray) "Gondi")
(set (intern "GRN" fontfile-ttx-eldoc-obarray) "Greenlandic")
(set (intern "GRO" fontfile-ttx-eldoc-obarray) "Garo")
(set (intern "GUA" fontfile-ttx-eldoc-obarray) "Guarani")
(set (intern "GUJ" fontfile-ttx-eldoc-obarray) "Gujarati")
(set (intern "HAI" fontfile-ttx-eldoc-obarray) "Haitian")
(set (intern "HAL" fontfile-ttx-eldoc-obarray) "Halam")
(set (intern "HAR" fontfile-ttx-eldoc-obarray) "Harauti")
(set (intern "HAU" fontfile-ttx-eldoc-obarray) "Hausa")
(set (intern "HAW" fontfile-ttx-eldoc-obarray) "Hawaiin")
(set (intern "HBN" fontfile-ttx-eldoc-obarray) "Hammer-Banna")
(set (intern "HIL" fontfile-ttx-eldoc-obarray) "Hiligaynon")
(set (intern "HIN" fontfile-ttx-eldoc-obarray) "Hindi")
(set (intern "HMA" fontfile-ttx-eldoc-obarray) "High Mari")
(set (intern "HND" fontfile-ttx-eldoc-obarray) "Hindko")
(set (intern "HO" fontfile-ttx-eldoc-obarray) "Ho")
(set (intern "HRI" fontfile-ttx-eldoc-obarray) "Harari")
(set (intern "HRV" fontfile-ttx-eldoc-obarray) "Croatian")
(set (intern "HUN" fontfile-ttx-eldoc-obarray) "Hungarian")
(set (intern "HYE" fontfile-ttx-eldoc-obarray) "Armenian")
(set (intern "IBO" fontfile-ttx-eldoc-obarray) "Igbo")
(set (intern "IJO" fontfile-ttx-eldoc-obarray) "Ijo")
(set (intern "ILO" fontfile-ttx-eldoc-obarray) "Ilokano")
(set (intern "IND" fontfile-ttx-eldoc-obarray) "Indonesian")
(set (intern "ING" fontfile-ttx-eldoc-obarray) "Ingush")
(set (intern "INU" fontfile-ttx-eldoc-obarray) "Inuktitut")
(set (intern "IPPH" fontfile-ttx-eldoc-obarray) "Phonetic transcription—IPA conventions")
(set (intern "IRI" fontfile-ttx-eldoc-obarray) "Irish")
(set (intern "IRT" fontfile-ttx-eldoc-obarray) "Irish Traditional")
(set (intern "ISL" fontfile-ttx-eldoc-obarray) "Icelandic")
(set (intern "ISM" fontfile-ttx-eldoc-obarray) "Inari Sami")
(set (intern "ITA" fontfile-ttx-eldoc-obarray) "Italian")
(set (intern "IWR" fontfile-ttx-eldoc-obarray) "Hebrew")
(set (intern "JAV" fontfile-ttx-eldoc-obarray) "Javanese")
(set (intern "JII" fontfile-ttx-eldoc-obarray) "Yiddish")
(set (intern "JAN" fontfile-ttx-eldoc-obarray) "Japanese")
(set (intern "JUD" fontfile-ttx-eldoc-obarray) "Judezmo")
(set (intern "JUL" fontfile-ttx-eldoc-obarray) "Jula")
(set (intern "KAB" fontfile-ttx-eldoc-obarray) "Kabardian")
(set (intern "KAC" fontfile-ttx-eldoc-obarray) "Kachchi")
(set (intern "KAL" fontfile-ttx-eldoc-obarray) "Kalenjin")
(set (intern "KAN" fontfile-ttx-eldoc-obarray) "Kannada")
(set (intern "KAR" fontfile-ttx-eldoc-obarray) "Karachay")
(set (intern "KAT" fontfile-ttx-eldoc-obarray) "Georgian")
(set (intern "KAZ" fontfile-ttx-eldoc-obarray) "Kazakh")
(set (intern "KEB" fontfile-ttx-eldoc-obarray) "Kebena")
(set (intern "KGE" fontfile-ttx-eldoc-obarray) "Khutsuri Georgian")
(set (intern "KHA" fontfile-ttx-eldoc-obarray) "Khakass")
(set (intern "KHK" fontfile-ttx-eldoc-obarray) "Khanty-Kazim")
(set (intern "KHM" fontfile-ttx-eldoc-obarray) "Khmer")
(set (intern "KHS" fontfile-ttx-eldoc-obarray) "Khanty-Shurishkar")
(set (intern "KHV" fontfile-ttx-eldoc-obarray) "Khanty-Vakhi")
(set (intern "KHW" fontfile-ttx-eldoc-obarray) "Khowar")
(set (intern "KIK" fontfile-ttx-eldoc-obarray) "Kikuyu")
(set (intern "KIR" fontfile-ttx-eldoc-obarray) "Kirghiz")
(set (intern "KIS" fontfile-ttx-eldoc-obarray) "Kisii")
(set (intern "KKN" fontfile-ttx-eldoc-obarray) "Kokni")
(set (intern "KLM" fontfile-ttx-eldoc-obarray) "Kalmyk")
(set (intern "KMB" fontfile-ttx-eldoc-obarray) "Kamba")
(set (intern "KMN" fontfile-ttx-eldoc-obarray) "Kumaoni")
(set (intern "KMO" fontfile-ttx-eldoc-obarray) "Komo")
(set (intern "KMS" fontfile-ttx-eldoc-obarray) "Komso")
(set (intern "KNR" fontfile-ttx-eldoc-obarray) "Kanuri")
(set (intern "KOD" fontfile-ttx-eldoc-obarray) "Kodagu")
(set (intern "KOH" fontfile-ttx-eldoc-obarray) "Korean Old Hangul")
(set (intern "KOK" fontfile-ttx-eldoc-obarray) "Konkani")
(set (intern "KON" fontfile-ttx-eldoc-obarray) "Kikongo")
(set (intern "KOP" fontfile-ttx-eldoc-obarray) "Komi-Permyak")
(set (intern "KOR" fontfile-ttx-eldoc-obarray) "Korean")
(set (intern "KOZ" fontfile-ttx-eldoc-obarray) "Komi-Zyrian")
(set (intern "KPL" fontfile-ttx-eldoc-obarray) "Kpelle")
(set (intern "KRI" fontfile-ttx-eldoc-obarray) "Krio")
(set (intern "KRK" fontfile-ttx-eldoc-obarray) "Karakalpak")
(set (intern "KRL" fontfile-ttx-eldoc-obarray) "Karelian")
(set (intern "KRM" fontfile-ttx-eldoc-obarray) "Karaim")
(set (intern "KRN" fontfile-ttx-eldoc-obarray) "Karen")
(set (intern "KRT" fontfile-ttx-eldoc-obarray) "Koorete")
(set (intern "KSH" fontfile-ttx-eldoc-obarray) "Kashmiri")
(set (intern "KSI" fontfile-ttx-eldoc-obarray) "Khasi")
(set (intern "KSM" fontfile-ttx-eldoc-obarray) "Kildin Sami")
(set (intern "KUI" fontfile-ttx-eldoc-obarray) "Kui")
(set (intern "KUL" fontfile-ttx-eldoc-obarray) "Kulvi")
(set (intern "KUM" fontfile-ttx-eldoc-obarray) "Kumyk")
(set (intern "KUR" fontfile-ttx-eldoc-obarray) "Kurdish")
(set (intern "KUU" fontfile-ttx-eldoc-obarray) "Kurukh")
(set (intern "KUY" fontfile-ttx-eldoc-obarray) "Kuy")
(set (intern "KYK" fontfile-ttx-eldoc-obarray) "Koryak")
(set (intern "LAD" fontfile-ttx-eldoc-obarray) "Ladin")
(set (intern "LAH" fontfile-ttx-eldoc-obarray) "Lahuli")
(set (intern "LAK" fontfile-ttx-eldoc-obarray) "Lak")
(set (intern "LAM" fontfile-ttx-eldoc-obarray) "Lambani")
(set (intern "LAO" fontfile-ttx-eldoc-obarray) "Lao")
(set (intern "LAT" fontfile-ttx-eldoc-obarray) "Latin")
(set (intern "LAZ" fontfile-ttx-eldoc-obarray) "Laz")
(set (intern "LCR" fontfile-ttx-eldoc-obarray) "L-Cree")
(set (intern "LDK" fontfile-ttx-eldoc-obarray) "Ladakhi")
(set (intern "LEZ" fontfile-ttx-eldoc-obarray) "Lezgi")
(set (intern "LIN" fontfile-ttx-eldoc-obarray) "Lingala")
(set (intern "LMA" fontfile-ttx-eldoc-obarray) "Low Mari")
(set (intern "LMB" fontfile-ttx-eldoc-obarray) "Limbu")
(set (intern "LMW" fontfile-ttx-eldoc-obarray) "Lomwe")
(set (intern "LSB" fontfile-ttx-eldoc-obarray) "Lower Sorbian")
(set (intern "LSM" fontfile-ttx-eldoc-obarray) "Lule Sami")
(set (intern "LTH" fontfile-ttx-eldoc-obarray) "Lithuanian")
(set (intern "LTZ" fontfile-ttx-eldoc-obarray) "Luxembourgish")
(set (intern "LUB" fontfile-ttx-eldoc-obarray) "Luba")
(set (intern "LUG" fontfile-ttx-eldoc-obarray) "Luganda")
(set (intern "LUH" fontfile-ttx-eldoc-obarray) "Luhya")
(set (intern "LUO" fontfile-ttx-eldoc-obarray) "Luo")
(set (intern "LVI" fontfile-ttx-eldoc-obarray) "Latvian")
(set (intern "MAJ" fontfile-ttx-eldoc-obarray) "Majang")
(set (intern "MAK" fontfile-ttx-eldoc-obarray) "Makua")
(set (intern "MAL" fontfile-ttx-eldoc-obarray) "Malayalam Traditional")
(set (intern "MAN" fontfile-ttx-eldoc-obarray) "Mansi")
(set (intern "MAP" fontfile-ttx-eldoc-obarray) "Mapudungun")
(set (intern "MAR" fontfile-ttx-eldoc-obarray) "Marathi")
(set (intern "MAW" fontfile-ttx-eldoc-obarray) "Marwari")
(set (intern "MBN" fontfile-ttx-eldoc-obarray) "Mbundu")
(set (intern "MCH" fontfile-ttx-eldoc-obarray) "Manchu")
(set (intern "MCR" fontfile-ttx-eldoc-obarray) "Moose Cree")
(set (intern "MDE" fontfile-ttx-eldoc-obarray) "Mende")
(set (intern "MEN" fontfile-ttx-eldoc-obarray) "Me'en")
(set (intern "MIZ" fontfile-ttx-eldoc-obarray) "Mizo")
(set (intern "MKD" fontfile-ttx-eldoc-obarray) "Macedonian")
(set (intern "MLE" fontfile-ttx-eldoc-obarray) "Male")
(set (intern "MLG" fontfile-ttx-eldoc-obarray) "Malagasy")
(set (intern "MLN" fontfile-ttx-eldoc-obarray) "Malinke")
(set (intern "MLR" fontfile-ttx-eldoc-obarray) "Malayalam Reformed")
(set (intern "MLY" fontfile-ttx-eldoc-obarray) "Malay")
(set (intern "MND" fontfile-ttx-eldoc-obarray) "Mandinka")
(set (intern "MNG" fontfile-ttx-eldoc-obarray) "Mongolian")
(set (intern "MNI" fontfile-ttx-eldoc-obarray) "Manipuri")
(set (intern "MNK" fontfile-ttx-eldoc-obarray) "Maninka")
(set (intern "MNX" fontfile-ttx-eldoc-obarray) "Manx Gaelic")
(set (intern "MOH" fontfile-ttx-eldoc-obarray) "Mohawk")
(set (intern "MOK" fontfile-ttx-eldoc-obarray) "Moksha")
(set (intern "MOL" fontfile-ttx-eldoc-obarray) "Moldavian")
(set (intern "MON" fontfile-ttx-eldoc-obarray) "Mon")
(set (intern "MOR" fontfile-ttx-eldoc-obarray) "Moroccan")
(set (intern "MRI" fontfile-ttx-eldoc-obarray) "Maori")
(set (intern "MTH" fontfile-ttx-eldoc-obarray) "Maithili")
(set (intern "MTS" fontfile-ttx-eldoc-obarray) "Maltese")
(set (intern "MUN" fontfile-ttx-eldoc-obarray) "Mundari")
(set (intern "NAG" fontfile-ttx-eldoc-obarray) "Naga-Assamese")
(set (intern "NAN" fontfile-ttx-eldoc-obarray) "Nanai")
(set (intern "NAS" fontfile-ttx-eldoc-obarray) "Naskapi")
(set (intern "NCR" fontfile-ttx-eldoc-obarray) "N-Cree")
(set (intern "NDB" fontfile-ttx-eldoc-obarray) "Ndebele")
(set (intern "NDG" fontfile-ttx-eldoc-obarray) "Ndonga")
(set (intern "NEP" fontfile-ttx-eldoc-obarray) "Nepali")
(set (intern "NEW" fontfile-ttx-eldoc-obarray) "Newari")
(set (intern "NGR" fontfile-ttx-eldoc-obarray) "Nagari")
(set (intern "NHC" fontfile-ttx-eldoc-obarray) "Norway House Cree")
(set (intern "NIS" fontfile-ttx-eldoc-obarray) "Nisi")
(set (intern "NIU" fontfile-ttx-eldoc-obarray) "Niuean")
(set (intern "NKL" fontfile-ttx-eldoc-obarray) "Nkole")
(set (intern "NKO" fontfile-ttx-eldoc-obarray) "N'Ko")
(set (intern "NLD" fontfile-ttx-eldoc-obarray) "Dutch")
(set (intern "NOG" fontfile-ttx-eldoc-obarray) "Nogai")
(set (intern "NOR" fontfile-ttx-eldoc-obarray) "Norwegian")
(set (intern "NSM" fontfile-ttx-eldoc-obarray) "Northern Sami")
(set (intern "NTA" fontfile-ttx-eldoc-obarray) "Northern Tai")
(set (intern "NTO" fontfile-ttx-eldoc-obarray) "Esperanto")
(set (intern "NYN" fontfile-ttx-eldoc-obarray) "Nynorsk")
(set (intern "OCI" fontfile-ttx-eldoc-obarray) "Occitan")
(set (intern "OCR" fontfile-ttx-eldoc-obarray) "Oji-Cree")
(set (intern "OJB" fontfile-ttx-eldoc-obarray) "Ojibway")
(set (intern "ORI" fontfile-ttx-eldoc-obarray) "Odia (formerly Oriya)")
(set (intern "ORO" fontfile-ttx-eldoc-obarray) "Oromo")
(set (intern "OSS" fontfile-ttx-eldoc-obarray) "Ossetian")
(set (intern "PAA" fontfile-ttx-eldoc-obarray) "Palestinian Aramaic")
(set (intern "PAL" fontfile-ttx-eldoc-obarray) "Pali")
(set (intern "PAN" fontfile-ttx-eldoc-obarray) "Punjabi")
(set (intern "PAP" fontfile-ttx-eldoc-obarray) "Palpa")
(set (intern "PAS" fontfile-ttx-eldoc-obarray) "Pashto")
(set (intern "PGR" fontfile-ttx-eldoc-obarray) "Polytonic Greek")
(set (intern "PIL" fontfile-ttx-eldoc-obarray) "Filipino")
(set (intern "PLG" fontfile-ttx-eldoc-obarray) "Palaung")
(set (intern "PLK" fontfile-ttx-eldoc-obarray) "Polish")
(set (intern "PRO" fontfile-ttx-eldoc-obarray) "Provencal")
(set (intern "PTG" fontfile-ttx-eldoc-obarray) "Portuguese")
(set (intern "QIN" fontfile-ttx-eldoc-obarray) "Chin")
(set (intern "RAJ" fontfile-ttx-eldoc-obarray) "Rajasthani")
(set (intern "RCR" fontfile-ttx-eldoc-obarray) "R-Cree")
(set (intern "RBU" fontfile-ttx-eldoc-obarray) "Russian Buriat")
(set (intern "RIA" fontfile-ttx-eldoc-obarray) "Riang")
(set (intern "RMS" fontfile-ttx-eldoc-obarray) "Rhaeto-Romanic")
(set (intern "ROM" fontfile-ttx-eldoc-obarray) "Romanian")
(set (intern "ROY" fontfile-ttx-eldoc-obarray) "Romany")
(set (intern "RSY" fontfile-ttx-eldoc-obarray) "Rusyn")
(set (intern "RUA" fontfile-ttx-eldoc-obarray) "Ruanda")
(set (intern "RUS" fontfile-ttx-eldoc-obarray) "Russian")
(set (intern "SAD" fontfile-ttx-eldoc-obarray) "Sadri")
(set (intern "SAN" fontfile-ttx-eldoc-obarray) "Sanskrit")
(set (intern "SAT" fontfile-ttx-eldoc-obarray) "Santali")
(set (intern "SAY" fontfile-ttx-eldoc-obarray) "Sayisi")
(set (intern "SEK" fontfile-ttx-eldoc-obarray) "Sekota")
(set (intern "SEL" fontfile-ttx-eldoc-obarray) "Selkup")
(set (intern "SGO" fontfile-ttx-eldoc-obarray) "Sango")
(set (intern "SHN" fontfile-ttx-eldoc-obarray) "Shan")
(set (intern "SIB" fontfile-ttx-eldoc-obarray) "Sibe")
(set (intern "SID" fontfile-ttx-eldoc-obarray) "Sidamo")
(set (intern "SIG" fontfile-ttx-eldoc-obarray) "Silte Gurage")
(set (intern "SKS" fontfile-ttx-eldoc-obarray) "Skolt Sami")
(set (intern "SKY" fontfile-ttx-eldoc-obarray) "Slovak")
(set (intern "SLA" fontfile-ttx-eldoc-obarray) "Slavey")
(set (intern "SLV" fontfile-ttx-eldoc-obarray) "Slovenian")
(set (intern "SML" fontfile-ttx-eldoc-obarray) "Somali")
(set (intern "SMO" fontfile-ttx-eldoc-obarray) "Samoan")
(set (intern "SNA" fontfile-ttx-eldoc-obarray) "Sena")
(set (intern "SND" fontfile-ttx-eldoc-obarray) "Sindhi")
(set (intern "SNH" fontfile-ttx-eldoc-obarray) "Sinhalese")
(set (intern "SNK" fontfile-ttx-eldoc-obarray) "Soninke")
(set (intern "SOG" fontfile-ttx-eldoc-obarray) "Sodo Gurage")
(set (intern "SOT" fontfile-ttx-eldoc-obarray) "Sotho")
(set (intern "SQI" fontfile-ttx-eldoc-obarray) "Albanian")
(set (intern "SRB" fontfile-ttx-eldoc-obarray) "Serbian")
(set (intern "SRK" fontfile-ttx-eldoc-obarray) "Saraiki")
(set (intern "SRR" fontfile-ttx-eldoc-obarray) "Serer")
(set (intern "SSL" fontfile-ttx-eldoc-obarray) "South Slavey")
(set (intern "SSM" fontfile-ttx-eldoc-obarray) "Southern Sami")
(set (intern "SUR" fontfile-ttx-eldoc-obarray) "Suri")
(set (intern "SVA" fontfile-ttx-eldoc-obarray) "Svan")
(set (intern "SVE" fontfile-ttx-eldoc-obarray) "Swedish")
(set (intern "SWA" fontfile-ttx-eldoc-obarray) "Swadaya Aramaic")
(set (intern "SWK" fontfile-ttx-eldoc-obarray) "Swahili")
(set (intern "SWZ" fontfile-ttx-eldoc-obarray) "Swazi")
(set (intern "SXT" fontfile-ttx-eldoc-obarray) "Sutu")
(set (intern "SYR" fontfile-ttx-eldoc-obarray) "Syriac")
(set (intern "TAB" fontfile-ttx-eldoc-obarray) "Tabasaran")
(set (intern "TAJ" fontfile-ttx-eldoc-obarray) "Tajiki")
(set (intern "TAM" fontfile-ttx-eldoc-obarray) "Tamil")
(set (intern "TAT" fontfile-ttx-eldoc-obarray) "Tatar")
(set (intern "TCR" fontfile-ttx-eldoc-obarray) "TH-Cree")
(set (intern "TEL" fontfile-ttx-eldoc-obarray) "Telugu")
(set (intern "TGN" fontfile-ttx-eldoc-obarray) "Tongan")
(set (intern "TGR" fontfile-ttx-eldoc-obarray) "Tigre")
(set (intern "TGY" fontfile-ttx-eldoc-obarray) "Tigrinya")
(set (intern "THA" fontfile-ttx-eldoc-obarray) "Thai")
(set (intern "THT" fontfile-ttx-eldoc-obarray) "Tahitian")
(set (intern "TIB" fontfile-ttx-eldoc-obarray) "Tibetan")
(set (intern "TKM" fontfile-ttx-eldoc-obarray) "Turkmen")
(set (intern "TMN" fontfile-ttx-eldoc-obarray) "Temne")
(set (intern "TNA" fontfile-ttx-eldoc-obarray) "Tswana")
(set (intern "TNE" fontfile-ttx-eldoc-obarray) "Tundra Nenets")
(set (intern "TNG" fontfile-ttx-eldoc-obarray) "Tonga")
(set (intern "TOD" fontfile-ttx-eldoc-obarray) "Todo")
(set (intern "TRK" fontfile-ttx-eldoc-obarray) "Turkish")
(set (intern "TSG" fontfile-ttx-eldoc-obarray) "Tsonga")
(set (intern "TUA" fontfile-ttx-eldoc-obarray) "Turoyo Aramaic")
(set (intern "TUL" fontfile-ttx-eldoc-obarray) "Tulu")
(set (intern "TUV" fontfile-ttx-eldoc-obarray) "Tuvin")
(set (intern "TWI" fontfile-ttx-eldoc-obarray) "Twi")
(set (intern "UDM" fontfile-ttx-eldoc-obarray) "Udmurt")
(set (intern "UKR" fontfile-ttx-eldoc-obarray) "Ukrainian")
(set (intern "URD" fontfile-ttx-eldoc-obarray) "Urdu")
(set (intern "USB" fontfile-ttx-eldoc-obarray) "Upper Sorbian")
(set (intern "UYG" fontfile-ttx-eldoc-obarray) "Uyghur")
(set (intern "UZB" fontfile-ttx-eldoc-obarray) "Uzbek")
(set (intern "VEN" fontfile-ttx-eldoc-obarray) "Venda")
(set (intern "VIT" fontfile-ttx-eldoc-obarray) "Vietnamese")
(set (intern "WA" fontfile-ttx-eldoc-obarray) "Wa")
(set (intern "WAG" fontfile-ttx-eldoc-obarray) "Wagdi")
(set (intern "WCR" fontfile-ttx-eldoc-obarray) "West-Cree")
(set (intern "WEL" fontfile-ttx-eldoc-obarray) "Welsh")
(set (intern "WLF" fontfile-ttx-eldoc-obarray) "Wolof")
(set (intern "XBD" fontfile-ttx-eldoc-obarray) "Tai Lue")
(set (intern "XHS" fontfile-ttx-eldoc-obarray) "Xhosa")
(set (intern "YAK" fontfile-ttx-eldoc-obarray) "Sakha")
(set (intern "YBA" fontfile-ttx-eldoc-obarray) "Yoruba")
(set (intern "YCR" fontfile-ttx-eldoc-obarray) "Y-Cree")
(set (intern "YIC" fontfile-ttx-eldoc-obarray) "Yi Classic")
(set (intern "YIM" fontfile-ttx-eldoc-obarray) "Yi Modern")
(set (intern "ZHH" fontfile-ttx-eldoc-obarray) "Chinese, Hong Kong SAR")
(set (intern "ZHP" fontfile-ttx-eldoc-obarray) "Chinese Phonetic")
(set (intern "ZHS" fontfile-ttx-eldoc-obarray) "Chinese Simplified")
(set (intern "ZHT" fontfile-ttx-eldoc-obarray) "Chinese Traditional")
(set (intern "ZND" fontfile-ttx-eldoc-obarray) "Zande")
(set (intern "ZUL" fontfile-ttx-eldoc-obarray) "Zulu")
(set (intern "arab" fontfile-ttx-eldoc-obarray) "Arabic")
(set (intern "armn" fontfile-ttx-eldoc-obarray) "Armenian")
(set (intern "avst" fontfile-ttx-eldoc-obarray) "Avestan")
(set (intern "bali" fontfile-ttx-eldoc-obarray) "Balinese")
(set (intern "bamu" fontfile-ttx-eldoc-obarray) "Bamum")
(set (intern "batk" fontfile-ttx-eldoc-obarray) "Batak")
(set (intern "beng" fontfile-ttx-eldoc-obarray) "Bengali")
(set (intern "bng2" fontfile-ttx-eldoc-obarray) "Bengali v.2")
(set (intern "bopo" fontfile-ttx-eldoc-obarray) "Bopomofo")
(set (intern "brai" fontfile-ttx-eldoc-obarray) "Braille")
(set (intern "brah" fontfile-ttx-eldoc-obarray) "Brahmi")
(set (intern "bugi" fontfile-ttx-eldoc-obarray) "Buginese")
(set (intern "buhd" fontfile-ttx-eldoc-obarray) "Buhid")
(set (intern "byzm" fontfile-ttx-eldoc-obarray) "Byzantine Music")
(set (intern "cans" fontfile-ttx-eldoc-obarray) "Canadian Syllabics")
(set (intern "cari" fontfile-ttx-eldoc-obarray) "Carian")
(set (intern "cakm" fontfile-ttx-eldoc-obarray) "Chakma")
(set (intern "cham" fontfile-ttx-eldoc-obarray) "Cham")
(set (intern "cher" fontfile-ttx-eldoc-obarray) "Cherokee")
(set (intern "hani" fontfile-ttx-eldoc-obarray) "CJK Ideographic")
(set (intern "copt" fontfile-ttx-eldoc-obarray) "Coptic")
(set (intern "cprt" fontfile-ttx-eldoc-obarray) "Cypriot Syllabary")
(set (intern "cyrl" fontfile-ttx-eldoc-obarray) "Cyrillic")
(set (intern "DFLT" fontfile-ttx-eldoc-obarray) "Default")
(set (intern "dsrt" fontfile-ttx-eldoc-obarray) "Deseret")
(set (intern "deva" fontfile-ttx-eldoc-obarray) "Devanagari")
(set (intern "dev2" fontfile-ttx-eldoc-obarray) "Devanagari v.2")
(set (intern "egyp" fontfile-ttx-eldoc-obarray) "Egyptian heiroglyphs")
(set (intern "ethi" fontfile-ttx-eldoc-obarray) "Ethiopic")
(set (intern "geor" fontfile-ttx-eldoc-obarray) "Georgian")
(set (intern "glag" fontfile-ttx-eldoc-obarray) "Glagolitic")
(set (intern "goth" fontfile-ttx-eldoc-obarray) "Gothic")
(set (intern "grek" fontfile-ttx-eldoc-obarray) "Greek")
(set (intern "gujr" fontfile-ttx-eldoc-obarray) "Gujarati")
(set (intern "gjr2" fontfile-ttx-eldoc-obarray) "Gujarati v.2")
(set (intern "guru" fontfile-ttx-eldoc-obarray) "Gurmukhi")
(set (intern "gur2" fontfile-ttx-eldoc-obarray) "Gurmukhi v.2")
(set (intern "hang" fontfile-ttx-eldoc-obarray) "Hangul")
(set (intern "jamo" fontfile-ttx-eldoc-obarray) "Hangul Jamo")
(set (intern "hano" fontfile-ttx-eldoc-obarray) "Hanunoo")
(set (intern "hebr" fontfile-ttx-eldoc-obarray) "Hebrew")
(set (intern "kana" fontfile-ttx-eldoc-obarray) "Hiragana")
(set (intern "armi" fontfile-ttx-eldoc-obarray) "Imperial Aramaic")
(set (intern "phli" fontfile-ttx-eldoc-obarray) "Inscriptional Pahlavi")
(set (intern "prti" fontfile-ttx-eldoc-obarray) "Inscriptional Parthian")
(set (intern "java" fontfile-ttx-eldoc-obarray) "Javanese")
(set (intern "kthi" fontfile-ttx-eldoc-obarray) "Kaithi")
(set (intern "knda" fontfile-ttx-eldoc-obarray) "Kannada")
(set (intern "knd2" fontfile-ttx-eldoc-obarray) "Kannada v.2")
(set (intern "kana" fontfile-ttx-eldoc-obarray) "Katakana")
(set (intern "kali" fontfile-ttx-eldoc-obarray) "Kayah Li")
(set (intern "khar" fontfile-ttx-eldoc-obarray) "Kharosthi")
(set (intern "khmr" fontfile-ttx-eldoc-obarray) "Khmer")
(set (intern "lao" fontfile-ttx-eldoc-obarray) "Lao")
(set (intern "latn" fontfile-ttx-eldoc-obarray) "Latin")
(set (intern "lepc" fontfile-ttx-eldoc-obarray) "Lepcha")
(set (intern "limb" fontfile-ttx-eldoc-obarray) "Limbu")
(set (intern "linb" fontfile-ttx-eldoc-obarray) "Linear B")
(set (intern "lisu" fontfile-ttx-eldoc-obarray) "Lisu (Fraser)")
(set (intern "lyci" fontfile-ttx-eldoc-obarray) "Lycian")
(set (intern "lydi" fontfile-ttx-eldoc-obarray) "Lydian")
(set (intern "mlym" fontfile-ttx-eldoc-obarray) "Malayalam")
(set (intern "mlm2" fontfile-ttx-eldoc-obarray) "Malayalam v.2")
(set (intern "mand" fontfile-ttx-eldoc-obarray) "Mandaic, Mandaean")
(set (intern "math" fontfile-ttx-eldoc-obarray) "Mathematical Alphanumeric Symbols")
(set (intern "mtei" fontfile-ttx-eldoc-obarray) "Meitei Mayek (Meithei, Meetei)")
(set (intern "merc" fontfile-ttx-eldoc-obarray) "Meroitic Cursive")
(set (intern "mero" fontfile-ttx-eldoc-obarray) "Meroitic Hieroglyphs")
(set (intern "mong" fontfile-ttx-eldoc-obarray) "Mongolian")
(set (intern "musc" fontfile-ttx-eldoc-obarray) "Musical Symbols")
(set (intern "mymr" fontfile-ttx-eldoc-obarray) "Myanmar")
(set (intern "talu" fontfile-ttx-eldoc-obarray) "New Tai Lue")
(set (intern "nko" fontfile-ttx-eldoc-obarray) "N'Ko")
(set (intern "ogam" fontfile-ttx-eldoc-obarray) "Ogham")
(set (intern "olck" fontfile-ttx-eldoc-obarray) "Ol Chiki")
(set (intern "ital" fontfile-ttx-eldoc-obarray) "Old Italic")
(set (intern "xpeo" fontfile-ttx-eldoc-obarray) "Old Persian Cuneiform")
(set (intern "sarb" fontfile-ttx-eldoc-obarray) "Old South Arabian")
(set (intern "orkh" fontfile-ttx-eldoc-obarray) "Old Turkic, Orkhon Runic")
(set (intern "orya" fontfile-ttx-eldoc-obarray) "Odia (formerly Oriya)")
(set (intern "ory2" fontfile-ttx-eldoc-obarray) "Odia v.2 (formerly Oriya v.2)")
(set (intern "osma" fontfile-ttx-eldoc-obarray) "Osmanya")
(set (intern "phag" fontfile-ttx-eldoc-obarray) "Phags-pa")
(set (intern "phnx" fontfile-ttx-eldoc-obarray) "Phoenician")
(set (intern "rjng" fontfile-ttx-eldoc-obarray) "Rejang")
(set (intern "runr" fontfile-ttx-eldoc-obarray) "Runic")
(set (intern "samr" fontfile-ttx-eldoc-obarray) "Samaritan")
(set (intern "saur" fontfile-ttx-eldoc-obarray) "Saurashtra")
(set (intern "shrd" fontfile-ttx-eldoc-obarray) "Sharada")
(set (intern "shaw" fontfile-ttx-eldoc-obarray) "Shavian")
(set (intern "sinh" fontfile-ttx-eldoc-obarray) "Sinhala")
(set (intern "sora" fontfile-ttx-eldoc-obarray) "Sora Sompeng")
(set (intern "xsux" fontfile-ttx-eldoc-obarray) "Sumero-Akkadian Cuneiform")
(set (intern "sund" fontfile-ttx-eldoc-obarray) "Sundanese")
(set (intern "sylo" fontfile-ttx-eldoc-obarray) "Syloti Nagri")
(set (intern "syrc" fontfile-ttx-eldoc-obarray) "Syriac")
(set (intern "tglg" fontfile-ttx-eldoc-obarray) "Tagalog")
(set (intern "tagb" fontfile-ttx-eldoc-obarray) "Tagbanwa")
(set (intern "tale" fontfile-ttx-eldoc-obarray) "Tai Le")
(set (intern "lana" fontfile-ttx-eldoc-obarray) "Tai Tham (Lanna)")
(set (intern "tavt" fontfile-ttx-eldoc-obarray) "Tai Viet")
(set (intern "takr" fontfile-ttx-eldoc-obarray) "Takri")
(set (intern "taml" fontfile-ttx-eldoc-obarray) "Tamil")
(set (intern "tml2" fontfile-ttx-eldoc-obarray) "Tamil v.2")
(set (intern "telu" fontfile-ttx-eldoc-obarray) "Telugu")
(set (intern "tel2" fontfile-ttx-eldoc-obarray) "Telugu v.2")
(set (intern "thaa" fontfile-ttx-eldoc-obarray) "Thaana")
(set (intern "thai" fontfile-ttx-eldoc-obarray) "Thai")
(set (intern "tibt" fontfile-ttx-eldoc-obarray) "Tibetan")
(set (intern "tfng" fontfile-ttx-eldoc-obarray) "Tifinagh")
(set (intern "ugar" fontfile-ttx-eldoc-obarray) "Ugaritic Cuneiform")
(set (intern "vai" fontfile-ttx-eldoc-obarray) "Vai")
(set (intern "yi" fontfile-ttx-eldoc-obarray) "Yi")

(defun fontfile-ttx-eldoc-function ()
    "Returns a doc string appropriate for the current context, or nil."
    (symbol-value (intern-soft (thing-at-point 'symbol)
                               fontfile-ttx-eldoc-obarray)))
